export const STORAGE_KEYS = {
  setup: "scoutx.setup.v1",
  location: "scoutx.location.v1",
  favorites: "scoutx.favorites.v1",
  notes: "scoutx.notes.v1",
  selectedGames: "scoutx.selectedGames.v1",
  abrechnungMeta: "scoutx.abrechnung.v1",
  presence: "scoutx.presence.v1",
  planHistory: "scoutx.planHistory.v1",
  hrworksImports: "scoutx.hrworksImports.v1",
  hrworksSelectors: "scoutx.hrworksSelectors.v1",
  hrworksPolicy: "scoutx.hrworksPolicy.v1",
  playerSheets: "scoutx.playerSheets.v1",
  scheduleWatch: "scoutx.scheduleWatch.v1",
  productDomain: "scoutx.product.v1",
};
